### ISSUE TITLE
新增的用户系统 重置密码发送邮件没成功

### ISSUE THREAD

**Issue by Zourunfa** [rxliuli/ai-assist#1]
新增的用户系统 重置密码发送邮件没成功

具体邮件 ：wangfengaf@gmail.com

**Comment by Zourunfa** [comment]
大哥 你这东西好  我想加入你 把 readme 写一下 基本的构建项目流程 可以吗

**Comment by Zourunfa** [comment]
能运行一下项目 我这菜鸡  帮你改改样式 适配啥的 也行吖

**Comment by Zourunfa** [comment]
我进入 packages 下面的chat 目录下 pnpm i  ， npm i 都不成功吖 
![image](https://user-images.githubusercontent.com/51783403/229835894-1aade856-36b7-4a73-a8e6-26349fa5274f.png)

**Comment by rxliuli** [comment]
ok，目前还有很多工作要做，晚点吾辈补下文档

todo list

 [x] 支持多行输入，可能支持动态行数，可能最大 4 行之类的，允许滚动条
- [x] 修复多行输入后，显示仍然是单行，需要添加样式 `white-space: pre-wrap;`
- [x] 删除标签页有点麻烦
- [x] 支持编辑会话标签页名字
- [x] 修复 markdown 预览没有复制代码的功能
- [x] 修复 markdown 预览出现了错误的滚动条
- [x] markdown 代码显示复制按钮
- [x] 切换会话时自动滚动到底部（或者保持记录的位置）
- [x] 左上角的新会话按钮过于不明显，默认设置为主色
- [x] “复制会话”过于显眼，改变为更不明显的颜色
- [x] feat: 支持快捷输入提示语
- [x] feat: i18n 支持
- [x] fix: 修复 textarea 不能滚动的错误
- [x] fix: 修复侧边栏过多时滚动条位置不对的错误
- [x] feat: 支持导入导出会话
- [x] feat: 快捷提示语支持虚拟无限滚动
- [x] feat: 快捷提示语支持搜索英文 -- 替换为英文优先
- [x] feat: 需要阻止并发发送消息
- [x] fix: 修复操作按钮列没有正确出现横向滚动条的问题
- [x] feat: 添加 google 分析功能的使用频率，避免无限制的增加 feature
- [x] feat: 支持中断输出，支持重新开始输出
- [x] feat: 支持自定义快捷提示语 -- 简化，不再优先处理 i18n 的问题
- [ ] feat: 同步本地的会话到远端
- [ ] docs: 更新文档以说明如何自定义提示语与分享
- [x] feat: 支持配置自己的 open api key
- [ ] fix: 修复 markdown 中 code 标签单行过长在移动端没有正确添加滚动条的错误
- [ ] feat: 在文档主页声明记录保留时间为 3 个月（主要是为了与官方的 tokens 使用消耗做对照，确定实际使用的 tokens 和官方收取的费用一致）
- [x] feat: 更换消息提示的模式，将提示消息作为系统消息
- [ ] feat: 提示词无法积累或导入，例如希望某个标签页只做翻译、润色、检查错别字、总结、或者根据接口生成 mock 数据之类的
- [ ] feat: 支持对消息做更多操作 <https://blog.miniasp.com/post/2023/02/28/Useful-tool-ChatGPT-Toolkit>
- [ ] feat: 当开始识别时有更明确的提示，当发生错误时有更明确的提示，支持发生错误后重新生成
- [ ] feat: 支持全语音交互模式，过滤扬声器输出的声音
- [x] feat: 支持手动指定 access token 的方式
- [x] feat: 选择少数好用的会话，例如苏格拉底的风格
- [x] fix: 修复语言选择文字过大不适的感觉
- [ ] feat: 使用时传递 user 参数，避免多个用户之间共享相同的会话上下文
- [ ] feat: 更新日志添加自定义中间件 bunyan-logger，ref: <https://cabinjs.com/>
- [ ] fix: 修复用户输入之后没有自动翻页的错误
- [ ] fix: 修复 markdown 展示最后一个 p 节点没有删除 `margin-bottom` 的问题
- [ ] fix: 修复输入框计算高度导致的光标丢失，滚动条总是移动到顶部
- [ ] feat: 记录每条消息使用的 tokens 便于后续统计评估成本
- [ ] feat: 所有消息创建完成之后都不允许再次编辑，避免后续统计成本变得非常困难
- [ ] feat: 使用 gpt-token-utils 替换 gpt-tokenizer，见效整个 bundle 的大小
- [ ] fix: 修复在前端没有提示密码、用户、邮箱验证的问题，避免一直无法通过验证但又不知道原因
- [ ] feat: 禁用 chat 之外的功能，避免用户误入该页面
- [ ] feat: 实现共享的 prompts，例如翻译、润色、检查错别字、总结、或者根据接口生成 mock 数据之类的

**Comment by Zourunfa** [comment]
牛的

**Comment by Zourunfa** [comment]
我现在很多同事都在用这个

**Comment by rxliuli** [comment]
> 我进入 packages 下面的 chat 目录下 pnpm i ， npm i 都不成功吖 ![image](https://user-images.githubusercontent.com/51783403/229835894-1aade856-36b7-4a73-a8e6-26349fa5274f.png)

启动项目的简单步骤

```sh
1. fork && git clone
2. pnpm i # 请务必注意网络问题，不要使用 npm 的非官方镜像（例如淘宝源）
3. 使用 docker 启动一个本地的 postgresql 数据库，使用 tsx 运行 packages/chat-server/scripts/pgsql.ts 脚本
4. 创建 packages/chat-server/.env 添加 OPENAI_API_KEY/DATABASE_URL 环境变量
5. 在 packages/chat-server/ 目录下 pnpm dev 运行服务端
6. 在 packages/chat/ 目录下 pnpm dev 运行客户端
7. 打开 http://localhost:5174/
```

有任何问题及时反馈

**Comment by Zourunfa** [comment]
我先搞

**Comment by rxliuli** [comment]
> 先自己认真搞 实在不懂再骚扰你

或者你可以不管 server 端，请直接配置 packages/chat/vite.config.ts 的 proxy 为 http://chat.ai-assist.moe/，这样你就不用关心 3-5 步了

**Comment by rxliuli** [comment]
> 加个微信 行不行 学习一下

吾辈创建了 discord 群，目前可能不考虑使用微信，ref: https://discord.gg/pMba8bsp

**Comment by Zourunfa** [comment]
太强了

**Comment by Zourunfa** [comment]
> > 加个微信 行不行 学习一下
> 
> 吾辈创建了 discord 群，目前可能不考虑使用微信，ref: https://discord.gg/pMba8bsp

![image](https://user-images.githubusercontent.com/51783403/229841722-c40b236c-cdb9-444a-bfd7-20466e8a382c.png)
刚刚注册 为啥就被禁用了

**Comment by rxliuli** [comment]
奇怪。。。discord 怎么也这样了，openai 最近似乎在疯狂封号，不知道什么鬼，可能羊毛被薅秃了

**Comment by Zourunfa** [comment]
是不是手机号不能选中国的

**Comment by Zourunfa** [comment]
keyi l

**Comment by rxliuli** [comment]
> ![image](https://user-images.githubusercontent.com/51783403/229851428-05578d1b-d5ce-4f78-ba1f-135ad446cb21.png) ![image](https://user-images.githubusercontent.com/51783403/229851471-4464f44b-a780-498d-963e-54ee6c55992a.png) dail 代理会时间超限 是我网络的问题吗

也许你需要正确的代理，这个服务部署位置是在加拿大。

科学上网参考耗子叔的那篇：https://github.com/haoel/haoel.github.io
建议你也可以尝试 proxifier 透明代理工具，它可以拦截所有网络请求并强制代理，即便程序本身不支持，例如 nodejs

**Comment by Zourunfa** [comment]
我有vpn 并配置了加拿大 
![image](https://user-images.githubusercontent.com/51783403/229855062-30e22311-d96d-41c4-bdcb-d9251c288c9d.png)
我是还需要一个 proxifier 透明代理工具  进行配置吗   上面那篇文章有点长 主要看哪部分

**Comment by Zourunfa** [comment]
或者我先尝试一下这个

 3. 启动本地的 docker，使用 tsx 运行 packages/chat-server/scripts/pgsql.ts 脚本启动一个本地的 postgresql 数据库
4. 创建 packages/chat-server/.env 添加 OPENAI_API_KEY/DATABASE_URL 环境变量，DATABASE_URL 示例 DATABASE_URL="postgres://postgres:postgrespw@localhost:5432/chat?schema=public"

**Comment by rxliuli** [comment]
> 我有 vpn 并配置了加拿大 ![image](https://user-images.githubusercontent.com/51783403/229855062-30e22311-d96d-41c4-bdcb-d9251c288c9d.png) 我是还需要一个 proxifier 透明代理工具 进行配置吗 上面那篇文章有点长 主要看哪部分

如果是 vpn 的话应该可以拦截系统所有的网络请求才对，主要是你需要确定 nodejs 发向 http://chat.ai-assist.moe/ 的流量都走了代理，你能在日志中看到么？

**Comment by rxliuli** [comment]
> 或者我先尝试一下这个
> 
> 3. 启动本地的 docker，使用 tsx 运行 packages/chat-server/scripts/pgsql.ts 脚本启动一个本地的 postgresql 数据库
> 4. 创建 packages/chat-server/.env 添加 OPENAI_API_KEY/DATABASE_URL 环境变量，DATABASE_URL 示例 DATABASE_URL="postgres://postgres:postgrespw@localhost:5432/chat?schema=public"

这个也要求你能够从 nodejs 连接到 openai 的服务器，网络问题都存在。。。

**Comment by Zourunfa** [comment]
![image](https://user-images.githubusercontent.com/51783403/229856586-2f025508-885d-4103-89c3-322b7c3921a6.png)
可以了 不过忒慢

**Comment by rxliuli** [comment]
> ![image](https://user-images.githubusercontent.com/51783403/229856586-2f025508-885d-4103-89c3-322b7c3921a6.png) 可以了 不过忒慢

这个吾辈晚点处理，需要看看怎么做一些优化性能

**Comment by Zourunfa** [comment]
我c 好像变快了

**Comment by Zourunfa** [comment]
但是 不稳定 我先改个小问题看看

**Comment by Zourunfa** [comment]
![image](https://user-images.githubusercontent.com/51783403/229860669-b5a57455-c4c8-48e3-9cb7-d28fec7fd93f.png)

**Comment by rxliuli** [comment]
release 0.5.3 支持密码重置

**Comment by rxliuli** [comment]
> > 我进入 packages 下面的 chat 目录下 pnpm i ， npm i 都不成功吖 ![image](https://user-images.githubusercontent.com/51783403/229835894-1aade856-36b7-4a73-a8e6-26349fa5274f.png)
> 
> 启动项目的简单步骤
> 
> ```shell
> 1. fork && git clone
> 2. pnpm i # 请务必注意网络问题，不要使用 npm 的非官方镜像（例如淘宝源）
> 3. 启动本地的 docker，使用 tsx 运行 packages/chat-server/scripts/pgsql.ts 脚本启动一个本地的 postgresql 数据库
> 4. 创建 packages/chat-server/.env 添加 OPENAI_API_KEY/DATABASE_URL 环境变量，DATABASE_URL 示例 DATABASE_URL="postgres://postgres:postgrespw@localhost:5432/chat?schema=public"
> 5. 在 packages/chat-server/ 目录下 pnpm dev 运行服务端
> 6. 在 packages/chat/ 目录下 pnpm dev 运行客户端
> 7. 打开 http://localhost:5174/
> ```
> 
> 有任何问题及时反馈

已添加到文档
http://docs.ai-assist.moe/chat/#%E5%BC%80%E5%8F%91
