### ISSUE TITLE
在chat-admin下面Pnpm dev 报错

### ISSUE THREAD

**Issue by Zourunfa** [rxliuli/ai-assist#9]
![image](https://user-images.githubusercontent.com/51783403/236656910-990b07b0-8243-4531-b875-fe13340e8652.png)

### 环境
1.node : v16.17.0
2.npm  8.15.0
3.windows 11

**Comment by rxliuli** [comment]
代码全路径不能包含中文

**Comment by Zourunfa** [comment]
> 代码全路径不能包含中文
老哥 我系统的安装好docker了 ，启动本地docker 这句话 是要创建一个本地镜像吗
![Uploading image.png…]()

**Comment by rxliuli** [comment]
看不到图片
